- name: Restart auditd
  ansible.builtin.systemd:
    name: auditd
    state: restarted


- name: Restart timer
  ansible.builtin.systemd:
    name: audit-fim.timer
    state: restarted
    daemon_reload: true

- name: Restart service
  ansible.builtin.systemd:
    name: audit-fim.service
    state: restarted
    daemon_reload: true
